name: CI/CD - Tests et déploiement Hugging Face

on:
  push:
    branches:
      - dev
      - main
      - hf-deploy

  pull_request:
    branches:
      - dev
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_KEY: sami
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/BDD_employees

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: BDD_employees
        ports:
          - 5432:5432

    steps:
      - name: Récupérer le code avec Git LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Télécharger les fichiers LFS
        run: git lfs pull

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer uv
        uses: astral-sh/setup-uv@v5

      - name: Installer les dépendances
        run: uv sync

      - name: Créer les tables PostgreSQL
        run: uv run python -m BDD.connexion

      - name: Lancer les tests avec couverture
        run: uv run pytest --cov=app --cov=BDD

  deploy_cd:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/hf-deploy'

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Déployer sur Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://oauth2:${HF_TOKEN}@huggingface.co/spaces/samss1010/api-employees-fastapi
          git push hf hf-deploy:main --force